sudo: required

language: bash

services:
  - docker

before_install:
  - export APP_IMAGE=db-extractor-logger
  - docker build -t $APP_IMAGE
  - docker run $APP_IMAGE composer ci

script:
  - docker-compose run --rm app
