version: '2'
services:
  app:
    build: .
    working_dir: /code
    command: sh -c 'composer install -n && composer ci'
  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: sh -c 'composer install -n && composer ci'
